# Generated by Django 4.1.5 on 2023-01-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articlemodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.CharField(default=12, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
