# Generated by Django 4.1.5 on 2023-01-29 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_comment_post_comment_active_comment_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
