# Generated by Django 4.1.5 on 2023-01-29 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_remove_comment_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=-21, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article.articlemodel'),
            preserve_default=False,
        ),
    ]
