# Generated by Django 4.1.5 on 2023-01-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
